#!/usr/bin/env bash

shopt -s nullglob

# This list generated by deleting .gitignore and running `git status` after a build
artifacts=(
    .eslintcache
    __pycache__
    #*/__pycache__
    #*/*/__pycache__
    #*/*/*/__pycache__
    config.gypi
    config.mk
    config.status
    deps/icu-tmp
    deps/npm/node_modules/node-gyp/gyp/pylib/gyp/__pycache__
    deps/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/__pycache__
    icu_config.gypi
    node
    node_trace.1.log
    out
    test/*/__pycache__
    test/addons/01_worker_support
    test/addons/02_function_arguments
    test/addons/03_callbacks
    test/addons/04_object_factory
    test/addons/05_function_factory
    test/addons/06_wrapping_c_objects
    test/addons/07_factory_of_wrapped_objects
    test/addons/08_passing_wrapped_objects_around
    tools/.cpplintstamp
    tools/.doclintstamp
    tools/.mdlintstamp
    tools/__pycache__
    tools/configure.d/__pycache__
    tools/doc/node_modules
    tools/inspector_protocol/__pycache__
    tools/inspector_protocol/jinja2/__pycache__
    tools/inspector_protocol/markupsafe/__pycache__
    tools/v8_gypfiles/__pycache__
)
shopt -u nullglob

from="/workspaces/node-prior"
to="/workspaces/node"
for artifact in "${artifacts[@]}" ; do
  echo "Copy build artifact from $from to $to: $artifact"
  cp -rp "$from/$artifact" "$to/$artifact"
  echo "Changing ownership of build artifact to match UID: $artifact"
  # VSCode updates the `build` user ID in the container to match host's user ID
  # This avoids volume mounting issues.
  # We must manually update owner of copied files
  sudo chown -R build "$to/$artifact"
done
